// Run against an already-started, disposable synthetic demo. This script never owns the server.
// NODE_PATH=/path/to/test/node_modules BROWSER_EXECUTABLE=/path/to/chrome node tests/browser-smoke.mjs
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';
const url=new URL(base);
assert(['127.0.0.1','localhost','[::1]'].includes(url.hostname),'Browser smoke must target loopback');
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/browser-smoke';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[],external=[];
context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
page.on('pageerror',e=>errors.push(e.message));
context.on('request',r=>{if(new URL(r.url()).origin!==url.origin)external.push(r.url());});
const saved=async p=>{await p.locator('#task-form, #upload-form, #item-form, #document-form, #document-state-form').waitFor({state:'detached'});await p.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();};
const reflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),await p.evaluate(()=>innerWidth),'Page must not overflow viewport');
try {
 await page.goto(base); await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 await page.keyboard.press('Tab'); assert.equal(await page.locator(':focus').innerText(),'Skip to main content');
 await page.keyboard.press('Enter'); assert.equal(await page.locator(':focus').getAttribute('id'),'main');
 await page.getByRole('link',{name:'Open workspace'}).first().click(); await page.getByRole('heading',{name:'At a glance'}).waitFor();
 await page.screenshot({path:`${output}/overview-desktop.png`,fullPage:true});
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByLabel('Task title',{exact:true}).fill('Review the handoff checklist');
 await page.getByLabel('Next action and context',{exact:true}).fill('Confirm documentation, discuss open questions, and record the agreed next step.');
 await page.getByLabel('Responsible participant',{exact:true}).selectOption('alex');
 await page.getByLabel('Status',{exact:true}).selectOption('In progress');
 await page.getByLabel('Due date (optional)',{exact:true}).fill('2026-11-15');
 await page.locator('input[name=links]').first().check();
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 let task=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Review the handoff checklist',exact:true})}).last();
 assert.match(await task.innerText(),/In progress/i); assert.match(await task.innerText(),/2026-11-15/);
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Status',{exact:true}).selectOption('Blocked');
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 assert.match(await task.innerText(),/Blocked/); await task.getByText('Task history (1 previous revision)',{exact:true}).click();
 assert.match(await task.innerText(),/In progress/i);
 await page.screenshot({path:`${output}/tasks-desktop.png`,fullPage:true});
 await page.setViewportSize({width:390,height:844}); await reflow(page);
 await page.screenshot({path:`${output}/tasks-mobile.png`,fullPage:true});
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Next action and context',{exact:true}).fill('Draft retained after a concurrent update.');
 const other=await context.newPage(); await other.goto(page.url());
 const otherTask=other.locator('article.record').filter({has:other.getByRole('heading',{name:'Review the handoff checklist',exact:true})}).last();
 await otherTask.getByRole('button',{name:'Update task',exact:true}).click();
 await other.getByLabel('Status',{exact:true}).selectOption('Done');
 await other.getByRole('button',{name:'Save task',exact:true}).click(); await saved(other);
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await page.getByText('Your draft is still here.',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('Next action and context',{exact:true}).inputValue(),'Draft retained after a concurrent update.');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 const upload=async (name,buffer)=>{await page.getByRole('button',{name:'Upload file',exact:true}).click();await page.getByLabel('Choose file',{exact:true}).setInputFiles({name,mimeType:'application/octet-stream',buffer});await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);};
 await upload('handoff-checklist.txt',Buffer.from('Synthetic handoff checklist. Version one.'));
 let file=page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).first();
 assert.match(await file.innerText(),/Demo released/i);
 const downloadEvent=page.waitForEvent('download');await file.getByRole('link',{name:'Download handoff-checklist.txt',exact:true}).click();
 const download=await downloadEvent;assert.equal(await readFile(await download.path(),'utf8'),'Synthetic handoff checklist. Version one.');
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 await page.getByLabel('Current protocol version',{exact:true}).selectOption({label:'handoff-checklist.txt · file version 1'});
 await page.getByLabel('Reason for selection or clearing',{exact:true}).fill('Use the reviewed first version as our working reference.');
 const designation=page.waitForResponse(r=>r.url().endsWith('/protocol')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save protocol designation',exact:true}).click();assert.equal((await designation).status(),200);
 await page.getByLabel('Reason for selection or clearing',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Document library',exact:true}).click();await file.waitFor();
 await file.getByRole('button',{name:'Upload new version',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'handoff-checklist.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic handoff checklist. Version two.')});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);
 assert.equal(await page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).count(),2);
 await page.getByRole('link',{name:'Overview',exact:true}).click();
 await page.locator('.protocol-title').getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).waitFor();
 assert.equal(await page.locator('.protocol-title').getByText('handoff-checklist.txt · file version 2',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('handoff-checklist.txt · file version 1',{exact:true}).check();
 await page.getByRole('button',{name:'Save task',exact:true}).click();await saved(page);
 const citation=task.getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).first();await citation.waitFor();
 await page.getByRole('button',{name:'+ Record a decision',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Retain the reviewed reference');
 await page.getByLabel('Decision, rationale, and alternatives',{exact:true}).fill('Keep the exact reviewed file version while preparing its successor.');
 await page.getByLabel('handoff-checklist.txt · file version 1',{exact:true}).check();
 await page.getByRole('button',{name:'Save record',exact:true}).click();await saved(page);
 await page.locator('article.record').filter({has:page.getByRole('heading',{name:'Retain the reviewed reference',exact:true})}).getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).waitFor();
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 await upload('synthetic-quarantined.pdf',Buffer.from('%PDF-1.4\nSynthetic quarantine test\n%%EOF'));
 const quarantined=page.locator('article.file-record').filter({hasText:'synthetic-quarantined.pdf'});
 assert.match(await quarantined.innerText(),/Quarantined/);assert.equal(await quarantined.getByRole('link').count(),0);
 await page.getByRole('button',{name:'Upload file',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'oversize.txt',mimeType:'text/plain',buffer:Buffer.alloc(512*1024+1,65)});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();
 await page.locator('#notice').getByText('Choose a synthetic file no larger than 512 KiB.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await reflow(page);
 await page.screenshot({path:`${output}/files-mobile.png`,fullPage:true});
 await page.locator('#identity').selectOption('admin'); await page.getByRole('heading',{name:'No study access',exact:true}).waitFor();
 await page.getByRole('link',{name:'Administration',exact:true}).click(); await page.getByRole('heading',{name:'Access & configuration',exact:true}).waitFor(); await reflow(page);
 // Administrative role does not grant study membership. Use two tabs to exercise stale configuration.
 await page.getByLabel('Synthetic identity',{exact:true}).selectOption('alex');
 await page.getByLabel('Application role',{exact:true}).selectOption('Administrator');
 const grant=page.waitForResponse(r=>r.url().endsWith('/api/admin/role')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save role',exact:true}).click();assert.equal((await grant).status(),200);
 await page.locator('#role-form').getByRole('option',{name:'Alex • synthetic researcher (Administrator)',exact:true}).waitFor({state:'attached'});
 const staleAdmin=await context.newPage();await staleAdmin.goto(base+'/#admin');await staleAdmin.getByRole('heading',{name:'Access & configuration',exact:true}).waitFor();
 const staleRevision=await staleAdmin.locator('#mapping-form').getAttribute('data-revision');
 // Saving an unchanged mapping advances configuration while leaving the boundary intact.
 const map=page.waitForResponse(r=>r.url().endsWith('/api/admin/mapping')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save mapping',exact:true}).click();assert.equal((await map).status(),200);
 await page.waitForFunction(old=>document.querySelector('#mapping-form')?.dataset.revision!==old,staleRevision);
 await staleAdmin.getByLabel('Stable group identifier',{exact:true}).fill('demo-group-b');
 const denied=staleAdmin.waitForResponse(r=>r.url().endsWith('/api/admin/mapping')&&r.request().method()==='POST');
 await staleAdmin.getByRole('button',{name:'Save mapping',exact:true}).click();assert.equal((await denied).status(),409);
 assert.equal(await staleAdmin.getByLabel('Stable group identifier',{exact:true}).inputValue(),'demo-group-b');
 await staleAdmin.close();
 await page.locator('#identity').selectOption('alex');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Open workspace'}).count(),1);
 assert.equal(await page.getByText('Beacon • Historical methods study',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 await page.getByRole('heading',{name:'Synthetic import rehearsal',exact:true}).waitFor();
 const manifest=await readFile(new URL('../fixtures/app-import.json',import.meta.url));
 const preview=async()=>{await page.getByLabel('Synthetic manifest JSON',{exact:true}).setInputFiles({name:'app-import.json',mimeType:'application/json',buffer:manifest});const response=page.waitForResponse(r=>r.url().endsWith('/imports/preview')&&r.request().method()==='POST');await page.getByRole('button',{name:'Preview import',exact:true}).click();const result=await response;assert.equal(result.status(),200);await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).waitFor();return result.json();};
 const apply=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/imports/apply')&&r.request().method()==='POST');await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).click();const result=await response;assert.equal(result.status(),200);await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).waitFor({state:'detached'});await page.getByText('Synthetic import applied. Review accepted and quarantined outcomes in the saved report.',{exact:true}).waitFor();return result.json();};
 const firstPreview=await preview();assert.equal(firstPreview.inputCount,7);assert.equal(firstPreview.counts.quarantined,0);const firstApply=await apply();assert.equal(firstApply.inputCount,firstPreview.inputCount);
 const repeatPreview=await preview();const repeatApply=await apply();assert.equal(repeatApply.inputCount,firstApply.inputCount);
 assert.equal(firstApply.counts.imported,7);assert.equal(repeatApply.counts.imported,0);assert.equal(repeatApply.counts.unchanged,7);
 console.log('IMPORT_COUNTS',JSON.stringify({first:firstApply.counts,repeat:repeatApply.counts}));
 await page.getByText('Saved import reports',{exact:true}).click();await page.locator('#import-reports .import-report').first().waitFor();
 await reflow(page);await page.screenshot({path:`${output}/import-mobile.png`,fullPage:true});
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 const importedV1=page.locator('article.file-record').filter({hasText:'synthetic-protocol-v1.txt'});await importedV1.waitFor();assert.match(await importedV1.innerText(),/File version 1/);assert.match(await importedV1.innerText(),/Feb 3, 2020/);
 const importedV2=page.locator('article.file-record').filter({hasText:'synthetic-protocol-v2.txt'});assert.match(await importedV2.innerText(),/File version 2/);
 assert.equal(await importedV1.count(),1);assert.equal(await importedV2.count(),1);
 await page.getByRole('link',{name:'Discussions',exact:true}).click();
 const importedDiscussion=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Imported protocol discussion',exact:true})});await importedDiscussion.waitFor();
 await importedDiscussion.getByRole('heading',{name:'Historical synthetic reply',exact:true}).waitFor();
 assert.match(await importedDiscussion.innerText(),/former-member/);assert.match(await importedDiscussion.innerText(),/Feb 3, 2020/);
 await importedDiscussion.getByRole('link',{name:'synthetic-protocol-v1.txt · file version 1',exact:true}).waitFor();
 const attachmentDownload=page.waitForEvent('download');await importedDiscussion.getByRole('link',{name:'Download synthetic-notes.txt',exact:true}).click();
 assert.equal(await readFile(await(await attachmentDownload).path(),'utf8'),'Synthetic attachment only.\n');
 await page.locator('#identity').selectOption('sam');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();
 assert.equal(await page.getByText('Imported protocol discussion',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Document library',exact:true}).click();assert.equal(await page.getByText('synthetic-protocol-v1.txt',{exact:true}).count(),0);
 await page.locator('#identity').selectOption('alex');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();await page.getByRole('link',{name:'Discussions',exact:true}).click();

 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:`${output}/imported-discussion-desktop.png`,fullPage:true});
 // Stable text families and study-specific review roles are independent of application administration.
 const switchStudyIdentity=async identity=>{await page.locator('#identity').selectOption(identity);await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();await page.getByRole('link',{name:'Document library',exact:true}).click();};
 const documentRecord=title=>page.locator('article.record').filter({has:page.getByRole('heading',{name:title,exact:true})});
 const reviewState=async(title,action,status,reason)=>{await documentRecord(title).getByRole('button',{name:action,exact:true}).click();await page.getByLabel('Reason for review-state change',{exact:true}).fill(reason);await page.getByRole('button',{name:'Confirm '+status,exact:true}).click();await saved(page);};
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 await page.getByRole('button',{name:'Add document',exact:true}).click();
 await page.getByLabel('Document title',{exact:true}).fill('Orientation review packet');
 await page.getByLabel('Version content',{exact:true}).fill('Initial synthetic orientation packet. Preserve this first version.');
 await page.getByRole('button',{name:'Save draft version',exact:true}).click();await saved(page);
 const familyBefore=await documentRecord('Orientation review packet').locator('.task-facts').innerText();
 await documentRecord('Orientation review packet').getByRole('button',{name:'Add revision',exact:true}).click();
 await page.getByLabel('Document title',{exact:true}).fill('Revised orientation packet');
 await page.getByLabel('Version content',{exact:true}).fill('Revised synthetic orientation packet with clear handoff responsibilities.');
 await page.getByRole('button',{name:'Save draft version',exact:true}).click();await saved(page);
 const familyAfter=await documentRecord('Revised orientation packet').locator('.task-facts').innerText();assert.equal(familyBefore,familyAfter);
 assert.match(await documentRecord('Revised orientation packet').innerText(),/Version 2/);
 assert.match(await documentRecord('Orientation review packet').innerText(),/Initial synthetic orientation packet/);
 await reviewState('Revised orientation packet','Submit for review','Review','Ready for a second participant to review.');
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Accept version',exact:true}).count(),0);
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Return to draft',exact:true}).count(),0);
 await switchStudyIdentity('reviewer');
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Accept version',exact:true}).count(),0);
 await reviewState('Revised orientation packet','Return to draft','Draft','Clarify who owns the remaining handoff question.');
 await switchStudyIdentity('alex');
 await reviewState('Revised orientation packet','Submit for review','Review','Ownership is clarified for the next review.');
 await switchStudyIdentity('lead');
 await reviewState('Revised orientation packet','Accept version','Accepted','Accept this internal working packet.');
 assert.match(await documentRecord('Revised orientation packet').locator('.task-facts').innerText(),/Accepted/i);
 await reviewState('Revised orientation packet','Supersede version','Superseded','Retain this version as the historical reference.');
 assert.match(await documentRecord('Revised orientation packet').locator('.task-facts').innerText(),/Superseded/i);
 await page.setViewportSize({width:390,height:844});await reflow(page);
 await page.screenshot({path:`${output}/document-review-mobile.png`,fullPage:true});
 // Capture once, then change live task/state. The returned captured packet stays byte-for-byte equivalent.
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();
 const seededSnapshot=page.locator('#handoff-list article').filter({has:page.getByRole('heading',{name:'Orientation handoff • synthetic example',exact:true})});
 await seededSnapshot.getByRole('button',{name:'View snapshot',exact:true}).click();
 await page.locator('#handoff-detail').getByRole('heading',{name:'Orientation handoff • synthetic example',exact:true}).waitFor();
 assert.match(await page.locator('#handoff-detail').innerText(),/Captured state: Accepted/i);
 const seedReviewHistory=page.locator('#handoff-detail summary').filter({hasText:'Captured review history'}).first();
 await seedReviewHistory.focus();await page.keyboard.press('Enter');
 assert.match(await page.locator('#handoff-detail').innerText(),/Draft → Review/);
 await page.keyboard.press('Enter');

 await page.getByLabel('Snapshot title',{exact:true}).fill('Reviewed orientation handoff');
 await page.getByLabel('Scope, assumptions, open questions, and owners',{exact:true}).fill('Synthetic scope: compare documentation approaches. Owner Alex; confirm the final checklist before resuming work.');
 const rejectedCapture=page.waitForResponse(r=>r.url().endsWith('/handoffs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Capture snapshot',exact:true}).click();assert.equal((await rejectedCapture).status(),400);
 await page.getByText('Your input is retained.',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('Snapshot title',{exact:true}).inputValue(),'Reviewed orientation handoff');
 await page.getByLabel('Evidence selection',{exact:true}).selectOption('explicit');
 await page.getByText('Choose explicit evidence (optional)',{exact:true}).click();
 await page.getByLabel('Revised orientation packet · document version 2',{exact:true}).check();
 await page.locator('#handoff-form label').filter({hasText:'Review the handoff checklist · task version'}).locator('input').check();
 const captureResponse=page.waitForResponse(r=>r.url().endsWith('/handoffs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Capture snapshot',exact:true}).click();const captureResult=await captureResponse;assert.equal(captureResult.status(),200);const captured=await captureResult.json();
 await page.getByText('Immutable handoff snapshot captured.',{exact:true}).waitFor();
 assert.equal(await page.locator(':focus').getAttribute('class'),'panel handoff-capture');
 await page.locator('#handoff-detail').getByRole('heading',{name:'Reviewed orientation handoff',exact:true}).waitFor();
 const capturedText=await page.locator('#handoff-detail').innerText();
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Next action and context',{exact:true}).fill('Live task changed after the fixed handoff capture.');
 await page.getByRole('button',{name:'Save task',exact:true}).click();await saved(page);
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 for(const stage of ['Closed','Active']){const oldStageForm=await page.locator('#stage-form').elementHandle();await page.getByLabel('Workspace stage',{exact:true}).selectOption(stage);const response=page.waitForResponse(r=>r.url().endsWith('/stage')&&r.request().method()==='POST');await page.getByRole('button',{name:'Update stage',exact:true}).click();assert.equal((await response).status(),200);await page.waitForFunction(form=>!form.isConnected,oldStageForm);await page.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();await page.locator('main[aria-busy="true"]').waitFor({state:'detached'});}
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();
 const snapshotCard=page.locator('#handoff-list article').filter({has:page.getByRole('heading',{name:'Reviewed orientation handoff',exact:true})});
 const snapshotResponse=page.waitForResponse(r=>r.url().endsWith('/handoffs/'+captured.id)&&r.request().method()==='GET');
 await snapshotCard.getByRole('button',{name:'View snapshot',exact:true}).click();const viewed=await(await snapshotResponse).json();assert.deepEqual(viewed,captured);
 await page.locator('#handoff-detail').getByRole('heading',{name:'Reviewed orientation handoff',exact:true}).waitFor();assert.equal(await page.locator('#handoff-detail').innerText(),capturedText);
 assert.equal(await page.locator('#handoff-detail').getByText('Live task changed after the fixed handoff capture.',{exact:true}).count(),0);
 await reflow(page);await page.screenshot({path:`${output}/handoff-mobile.png`,fullPage:true});
 assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
 console.log('PASS: keyboard skip link, structured task create/edit/history/evidence, conflict draft recovery, identity isolation, mobile reflow, upload/download bytes and versions, quarantine, oversize error, explicit protocol retention, exact file citations, stale admin rejection, connected import preview/apply/repeat, stable document families and review roles, immutable handoff after edits and lifecycle changes, no page errors or external requests.');
} finally {await browser.close();}
