// Run against an already-started, disposable synthetic demo. This script never owns the server.
// NODE_PATH=/path/to/test/node_modules BROWSER_EXECUTABLE=/path/to/chrome node tests/browser-smoke.mjs
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';
const url=new URL(base);
assert(['127.0.0.1','localhost','[::1]'].includes(url.hostname),'Browser smoke must target loopback');
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/browser-smoke';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[],external=[];
context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
page.on('pageerror',e=>errors.push(e.message));
context.on('request',r=>{if(new URL(r.url()).origin!==url.origin)external.push(r.url());});
const saved=async p=>{await p.locator('#task-form, #upload-form').waitFor({state:'detached'});await p.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();};
const reflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),await p.evaluate(()=>innerWidth),'Page must not overflow viewport');
try {
 await page.goto(base); await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 await page.keyboard.press('Tab'); assert.equal(await page.locator(':focus').innerText(),'Skip to main content');
 await page.keyboard.press('Enter'); assert.equal(await page.locator(':focus').getAttribute('id'),'main');
 await page.getByRole('link',{name:'Open workspace'}).first().click(); await page.getByRole('heading',{name:'At a glance'}).waitFor();
 await page.screenshot({path:`${output}/overview-desktop.png`,fullPage:true});
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByLabel('Task title',{exact:true}).fill('Review the handoff checklist');
 await page.getByLabel('Next action and context',{exact:true}).fill('Confirm documentation, discuss open questions, and record the agreed next step.');
 await page.getByLabel('Responsible participant',{exact:true}).selectOption('alex');
 await page.getByLabel('Status',{exact:true}).selectOption('In progress');
 await page.getByLabel('Due date (optional)',{exact:true}).fill('2026-11-15');
 await page.locator('input[name=links]').first().check();
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 let task=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Review the handoff checklist',exact:true})}).last();
 assert.match(await task.innerText(),/In progress/i); assert.match(await task.innerText(),/2026-11-15/);
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Status',{exact:true}).selectOption('Blocked');
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 assert.match(await task.innerText(),/Blocked/); await task.getByText('Task history (1 previous revision)',{exact:true}).click();
 assert.match(await task.innerText(),/In progress/i);
 await page.screenshot({path:`${output}/tasks-desktop.png`,fullPage:true});
 await page.setViewportSize({width:390,height:844}); await reflow(page);
 await page.screenshot({path:`${output}/tasks-mobile.png`,fullPage:true});
 await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Next action and context',{exact:true}).fill('Draft retained after a concurrent update.');
 const other=await context.newPage(); await other.goto(page.url());
 const otherTask=other.locator('article.record').filter({has:other.getByRole('heading',{name:'Review the handoff checklist',exact:true})}).last();
 await otherTask.getByRole('button',{name:'Update task',exact:true}).click();
 await other.getByLabel('Status',{exact:true}).selectOption('Done');
 await other.getByRole('button',{name:'Save task',exact:true}).click(); await saved(other);
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await page.getByText('Your draft is still here.',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('Next action and context',{exact:true}).inputValue(),'Draft retained after a concurrent update.');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 const upload=async (name,buffer)=>{await page.getByRole('button',{name:'Upload file',exact:true}).click();await page.getByLabel('Choose file',{exact:true}).setInputFiles({name,mimeType:'application/octet-stream',buffer});await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);};
 await upload('handoff-checklist.txt',Buffer.from('Synthetic handoff checklist. Version one.'));
 let file=page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).first();
 assert.match(await file.innerText(),/Demo released/i);
 const downloadEvent=page.waitForEvent('download');await file.getByRole('link',{name:'Download handoff-checklist.txt',exact:true}).click();
 const download=await downloadEvent;assert.equal(await readFile(await download.path(),'utf8'),'Synthetic handoff checklist. Version one.');
 await file.getByRole('button',{name:'Upload new version',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'handoff-checklist.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic handoff checklist. Version two.')});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);
 assert.equal(await page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).count(),2);
 await upload('synthetic-quarantined.pdf',Buffer.from('%PDF-1.4\nSynthetic quarantine test\n%%EOF'));
 const quarantined=page.locator('article.file-record').filter({hasText:'synthetic-quarantined.pdf'});
 assert.match(await quarantined.innerText(),/Quarantined/);assert.equal(await quarantined.getByRole('link').count(),0);
 await page.getByRole('button',{name:'Upload file',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'oversize.txt',mimeType:'text/plain',buffer:Buffer.alloc(512*1024+1,65)});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();
 await page.locator('#notice').getByText('Choose a synthetic file no larger than 512 KiB.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await reflow(page);
 await page.screenshot({path:`${output}/files-mobile.png`,fullPage:true});
 await page.locator('#identity').selectOption('admin'); await page.getByRole('heading',{name:'No study access',exact:true}).waitFor();
 await page.getByRole('link',{name:'Administration',exact:true}).click(); await page.getByRole('heading',{name:'Access & configuration',exact:true}).waitFor(); await reflow(page);
 assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
 console.log('PASS: keyboard skip link, structured task create/edit/history/evidence, conflict draft recovery, identity isolation, mobile reflow, upload/download bytes and versions, quarantine, oversize error, no page errors or external requests.');
} finally {await browser.close();}
