// Run against an already-started, disposable synthetic demo. This script never owns the server.
// NODE_PATH=/path/to/test/node_modules BROWSER_EXECUTABLE=/path/to/chrome node tests/browser-smoke.mjs
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';
const url=new URL(base);
assert(['127.0.0.1','localhost','[::1]'].includes(url.hostname),'Browser smoke must target loopback');
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/browser-smoke';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
context.setDefaultTimeout(15000);
const errors=[],external=[];
context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
page.on('pageerror',e=>errors.push(e.message));
context.on('request',r=>{if(new URL(r.url()).origin!==url.origin)external.push(r.url());});
const saved=async p=>{await p.locator('#task-form, #upload-form, #item-form, #document-form, #document-state-form, #typed-decision-form').waitFor({state:'detached'});await p.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();};
// Resolve a single immutable record before opening any collapsed ancestors.
const revealHistory=async record=>{await record.waitFor({state:'attached'});const id=await record.getAttribute('id');const exact=id?page.locator('[id='+JSON.stringify(id)+']'):record;for(const disclosure of await exact.locator('xpath=ancestor::details').all())if(await disclosure.getAttribute('open')===null)await disclosure.locator(':scope > summary').click();await exact.waitFor({state:'visible'});return exact;};
const revealRecord=async record=>{await page.getByRole('heading',{name:'Tasks & decisions',exact:true}).waitFor();await revealHistory(record);};
const reflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),await p.evaluate(()=>innerWidth),'Page must not overflow viewport');
async function auditPage(label){
 if(process.env.HUB_BROWSER_AXE!=='true')return;
 const AxeBuilder=require('@axe-core/playwright').default;
 const audit=await new AxeBuilder({page}).analyze();
 const violations=audit.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));
 assert.deepEqual(violations,[],label+' accessibility findings');console.log('AXE: '+label+' — 0 violations');
}
// Focus mode rechecks navigation against the disposable state created by the full suite.
async function verifyExactIdeaLinks(){
 await page.goto(base);await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 let exactVersion;
 for(let pass=0;pass<2;pass++){
  await page.locator('#search').fill('Checklist first');await page.locator('#search-form').getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('heading',{name:'Search results',exact:true}).waitFor();
  const result=page.getByRole('link',{name:'Checklist first',exact:true});const href=await result.getAttribute('href');assert.match(href,/\/idea\/board-[^/]+\/[^/]+$/);exactVersion=decodeURIComponent(href.split('/').at(-1));
  await result.click();await page.locator('#board-version-'+exactVersion).waitFor();assert.equal(await page.locator(':focus').getAttribute('id'),'board-version-'+exactVersion);assert.match(await page.locator('#board-version-'+exactVersion).innerText(),/Checklist first/);
 }
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByLabel('Task title',{exact:true}).fill('Follow the original brainstorming proposal');await page.getByLabel('Next action and context',{exact:true}).fill('Preserve the exact original idea as the supporting reference.');
 await page.locator('input[name=links][value="'+exactVersion+'"]').check();await page.getByRole('button',{name:'Save task',exact:true}).click();await saved(page);
 const record=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Follow the original brainstorming proposal',exact:true})}).last();
 await record.getByRole('link',{name:'Checklist first · idea version 1',exact:true}).click();await page.locator('#board-version-'+exactVersion).waitFor();assert.equal(await page.locator(':focus').getAttribute('id'),'board-version-'+exactVersion);
 await page.screenshot({path:`${output}/exact-idea-reference.png`,fullPage:true});
 console.log('PASS: search and same-hash search reopen the exact historical idea version; task evidence focuses the same version.');
}
try {
 if(process.env.HUB_BROWSER_FOCUS==='idea-links'){await verifyExactIdeaLinks();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);}else{
 await page.goto(base); await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 await page.keyboard.press('Tab'); assert.equal(await page.locator(':focus').innerText(),'Skip to main content');
 await page.keyboard.press('Enter'); assert.equal(await page.locator(':focus').getAttribute('id'),'main');
 await page.getByRole('link',{name:'Open workspace'}).first().click(); await page.getByRole('heading',{name:'At a glance'}).waitFor();
 await page.screenshot({path:`${output}/overview-desktop.png`,fullPage:true});
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await page.getByRole('button',{name:'Add task',exact:true}).click();
 await page.getByLabel('Task title',{exact:true}).fill('Review the handoff checklist');
 await page.getByLabel('Next action and context',{exact:true}).fill('Confirm documentation, discuss open questions, and record the agreed next step.');
 await page.getByLabel('Responsible participant',{exact:true}).selectOption('alex');
 await page.getByLabel('Status',{exact:true}).selectOption('In progress');
 await page.getByLabel('Due date (optional)',{exact:true}).fill('2026-11-15');
 await page.locator('input[name=links]').first().check();
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 let task=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Review the handoff checklist',exact:true,includeHidden:true})}).last();
 assert.match(await task.innerText(),/In progress/i); assert.match(await task.innerText(),/2026-11-15/);
 await revealRecord(task);await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Status',{exact:true}).selectOption('Blocked');
 await page.getByRole('button',{name:'Save task',exact:true}).click(); await saved(page);
 assert.match(await task.innerText(),/Blocked/); await task.getByText('Task history (1 previous revision)',{exact:true}).click();
 assert.match(await task.innerText(),/In progress/i);
 await page.screenshot({path:`${output}/tasks-desktop.png`,fullPage:true});
 await page.setViewportSize({width:390,height:844}); await reflow(page);
 await page.screenshot({path:`${output}/tasks-mobile.png`,fullPage:true});
 await revealRecord(task);await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Next action and context',{exact:true}).fill('Draft retained after a concurrent update.');
 const other=await context.newPage(); await other.goto(page.url());
 const otherTask=other.locator('article.record').filter({has:other.getByRole('heading',{name:'Review the handoff checklist',exact:true,includeHidden:true})}).last();
 await otherTask.getByRole('button',{name:'Update task',exact:true}).click();
 await other.getByLabel('Status',{exact:true}).selectOption('Done');
 await other.getByRole('button',{name:'Save task',exact:true}).click(); await saved(other);
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await page.getByText('Your draft is still here.',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('Next action and context',{exact:true}).inputValue(),'Draft retained after a concurrent update.');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 const upload=async (name,buffer)=>{await page.getByRole('button',{name:'Upload file',exact:true}).click();await page.getByLabel('Choose file',{exact:true}).setInputFiles({name,mimeType:'application/octet-stream',buffer});await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);};
 await upload('handoff-checklist.txt',Buffer.from('Synthetic handoff checklist. Version one.'));
 let file=page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).first();
 assert.match(await file.innerText(),/Demo released/i);
 const downloadEvent=page.waitForEvent('download');await file.getByRole('link',{name:'Download handoff-checklist.txt',exact:true}).click();
 const download=await downloadEvent;assert.equal(await readFile(await download.path(),'utf8'),'Synthetic handoff checklist. Version one.');
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 await page.getByLabel('Current protocol version',{exact:true}).selectOption({label:'handoff-checklist.txt · file version 1'});
 await page.getByLabel('Reason for selection or clearing',{exact:true}).fill('Use the reviewed first version as our working reference.');
 const designation=page.waitForResponse(r=>r.url().endsWith('/protocol')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save protocol designation',exact:true}).click();assert.equal((await designation).status(),200);
 await page.getByLabel('Reason for selection or clearing',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Document library',exact:true}).click();await file.waitFor();
 await file.getByRole('button',{name:'Upload new version',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'handoff-checklist.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic handoff checklist. Version two.')});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();await saved(page);
 assert.equal(await page.locator('article.file-record').filter({hasText:'handoff-checklist.txt'}).count(),2);
 await page.getByRole('link',{name:'Overview',exact:true}).click();
 await page.locator('.protocol-title').getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).waitFor();
 assert.equal(await page.locator('.protocol-title').getByText('handoff-checklist.txt · file version 2',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await revealRecord(task);await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('handoff-checklist.txt · file version 1',{exact:true}).check();
 await page.getByRole('button',{name:'Save task',exact:true}).click();await saved(page);
 await revealRecord(task);const citation=task.getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).first();await citation.waitFor();
 await page.getByRole('button',{name:'+ Record a decision',exact:true}).click();
 await page.getByLabel('Decision title',{exact:true}).fill('Retain the reviewed reference');
 await page.getByLabel('Decision and rationale',{exact:true}).fill('Keep the exact reviewed file version while preparing its successor.');
 await page.getByLabel('handoff-checklist.txt · file version 1',{exact:true}).check();
 await page.getByRole('button',{name:'Save decision',exact:true}).click();await saved(page);
 await page.locator('article.record').filter({has:page.getByRole('heading',{name:'Retain the reviewed reference',exact:true})}).getByRole('link',{name:'handoff-checklist.txt · file version 1',exact:true}).waitFor();
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 await upload('synthetic-quarantined.pdf',Buffer.from('%PDF-1.4\nSynthetic quarantine test\n%%EOF'));
 const quarantined=page.locator('article.file-record').filter({hasText:'synthetic-quarantined.pdf'});
 assert.match(await quarantined.innerText(),/Quarantined/);assert.equal(await quarantined.getByRole('link').count(),0);
 await page.getByRole('button',{name:'Upload file',exact:true}).click();
 await page.getByLabel('Choose file',{exact:true}).setInputFiles({name:'oversize.txt',mimeType:'text/plain',buffer:Buffer.alloc(512*1024+1,65)});
 await page.locator('#upload-form').getByRole('button',{name:'Upload file',exact:true}).click();
 await page.locator('#notice').getByText('Choose a synthetic file no larger than 512 KiB.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await reflow(page);
 await page.screenshot({path:`${output}/files-mobile.png`,fullPage:true});
 await page.locator('#identity').selectOption('admin'); await page.getByRole('heading',{name:'No study access',exact:true}).waitFor();
 await page.getByRole('link',{name:'Administration',exact:true}).click(); await page.getByRole('heading',{name:'Access & configuration',exact:true}).waitFor(); await reflow(page);
 console.log('PASS: task, file and protocol workflows');
 // Administrative role does not grant study membership. Use two tabs to exercise stale configuration.
 await page.getByLabel('Synthetic identity',{exact:true}).selectOption('alex');
 await page.getByLabel('Application role',{exact:true}).selectOption('Administrator');
 const grant=page.waitForResponse(r=>r.url().endsWith('/api/admin/role')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save role',exact:true}).click();assert.equal((await grant).status(),200);
 await page.locator('#role-form').getByRole('option',{name:'Alex • synthetic researcher (Administrator)',exact:true}).waitFor({state:'attached'});
 const staleAdmin=await context.newPage();await staleAdmin.goto(base+'/#admin');await staleAdmin.getByRole('heading',{name:'Access & configuration',exact:true}).waitFor();
 const staleRevision=await staleAdmin.locator('#mapping-form').getAttribute('data-revision');
 await staleAdmin.getByLabel('Stable group identifier',{exact:true}).fill('demo-group-b');await page.bringToFront();
 // Saving an unchanged mapping advances configuration while leaving the boundary intact.
 const map=page.waitForResponse(r=>r.url().endsWith('/api/admin/mapping')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Save mapping',exact:true}).click();assert.equal((await map).status(),200);
 await page.waitForFunction(old=>document.querySelector('#mapping-form')?.dataset.revision!==old,staleRevision);
 await staleAdmin.bringToFront();await staleAdmin.getByRole('heading',{name:'Retained drafts for this identity',exact:true}).waitFor();
 const retainedMapping=staleAdmin.waitForEvent('download');await staleAdmin.getByRole('button',{name:/^Download retained draft/}).click();assert.match(await readFile(await(await retainedMapping).path(),'utf8'),/demo-group-b/);
 const adminSession=await(await context.request.get(base+'/api/session')).json();const denied=await context.request.post(base+'/api/admin/mapping',{headers:{'X-CSRF-TOKEN':adminSession.csrf,'X-HUB-SESSION':adminSession.sessionContext},data:{studyId:'atlas',groupId:'demo-group-b',expectedRevision:Number(staleRevision),requestId:crypto.randomUUID()}});assert.equal(denied.status(),409);
 await staleAdmin.close();await page.bringToFront();
 await page.locator('#identity').selectOption('alex');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Open workspace'}).count(),1);
 assert.equal(await page.getByText('Beacon • Historical methods study',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 await page.getByRole('heading',{name:'Synthetic import rehearsal',exact:true}).waitFor();
 const manifest=await readFile(new URL('../fixtures/app-import.json',import.meta.url));
 const preview=async()=>{await page.getByLabel('Synthetic manifest JSON',{exact:true}).setInputFiles({name:'app-import.json',mimeType:'application/json',buffer:manifest});const response=page.waitForResponse(r=>r.url().endsWith('/imports/preview')&&r.request().method()==='POST');await page.getByRole('button',{name:'Preview import',exact:true}).click();const result=await response;assert.equal(result.status(),200);await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).waitFor();return result.json();};
 const apply=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/imports/apply')&&r.request().method()==='POST');await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).click();const result=await response;assert.equal(result.status(),200);await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).waitFor({state:'detached'});await page.getByText('Synthetic import applied. Review accepted and quarantined outcomes in the saved report.',{exact:true}).waitFor();return result.json();};
 const firstPreview=await preview();assert.equal(firstPreview.inputCount,7);assert.equal(firstPreview.counts.quarantined,0);const firstApply=await apply();assert.equal(firstApply.inputCount,firstPreview.inputCount);
 const repeatPreview=await preview();const repeatApply=await apply();assert.equal(repeatApply.inputCount,firstApply.inputCount);
 assert.equal(firstApply.counts.imported,7);assert.equal(repeatApply.counts.imported,0);assert.equal(repeatApply.counts.unchanged,7);
 console.log('IMPORT_COUNTS',JSON.stringify({first:firstApply.counts,repeat:repeatApply.counts}));
 await page.getByText('Saved import reports',{exact:true}).click();await page.locator('#import-reports .import-report').first().waitFor();
 await reflow(page);await page.screenshot({path:`${output}/import-mobile.png`,fullPage:true});
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 const importedV1=page.locator('article.file-record').filter({hasText:'synthetic-protocol-v1.txt'});await revealHistory(importedV1);assert.match(await importedV1.innerText(),/File version 1/);assert.match(await importedV1.innerText(),/Feb 3, 2020/);
 const importedV2=page.locator('article.file-record').filter({hasText:'synthetic-protocol-v2.txt'});assert.match(await importedV2.innerText(),/File version 2/);
 assert.equal(await importedV1.count(),1);assert.equal(await importedV2.count(),1);
 await page.getByRole('link',{name:'Discussions',exact:true}).click();
 const importedDiscussion=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Imported protocol discussion',exact:true})});await importedDiscussion.waitFor();
 await importedDiscussion.getByRole('heading',{name:'Historical synthetic reply',exact:true}).waitFor();
 assert.match(await importedDiscussion.innerText(),/former-member/);assert.match(await importedDiscussion.innerText(),/Feb 3, 2020/);
 await importedDiscussion.getByRole('link',{name:'synthetic-protocol-v1.txt · file version 1',exact:true}).waitFor();
 const attachmentDownload=page.waitForEvent('download');await importedDiscussion.getByRole('link',{name:'Download synthetic-notes.txt',exact:true}).click();
 assert.equal(await readFile(await(await attachmentDownload).path(),'utf8'),'Synthetic attachment only.\n');
 await page.locator('#identity').selectOption('sam');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
 await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();
 assert.equal(await page.getByText('Imported protocol discussion',{exact:true}).count(),0);
 await page.getByRole('link',{name:'Document library',exact:true}).click();assert.equal(await page.getByText('synthetic-protocol-v1.txt',{exact:true}).count(),0);
 await page.locator('#identity').selectOption('alex');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();await page.getByRole('link',{name:'Discussions',exact:true}).click();

 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:`${output}/imported-discussion-desktop.png`,fullPage:true});
 console.log('PASS: configuration concurrency and connected import fidelity');
 // Stable text families and study-specific review roles are independent of application administration.
 const switchStudyIdentity=async identity=>{await page.locator('#identity').selectOption(identity);await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();await page.getByRole('link',{name:'Document library',exact:true}).click();};
 const documentRecord=title=>page.locator('article.record').filter({has:page.getByRole('heading',{name:title,exact:true,includeHidden:true})});
 const reviewState=async(title,action,status,reason)=>{await revealHistory(documentRecord(title));await documentRecord(title).getByRole('button',{name:action,exact:true}).click();await page.getByLabel('Reason for review-state change',{exact:true}).fill(reason);await page.getByRole('button',{name:'Confirm '+status,exact:true}).click();await saved(page);};
 await page.getByRole('link',{name:'Document library',exact:true}).click();
 await page.getByRole('button',{name:'Add document',exact:true}).click();
 await page.getByLabel('Document title',{exact:true}).fill('Orientation review packet');
 await page.getByLabel('Version content',{exact:true}).fill('Initial synthetic orientation packet. Preserve this first version.');
 await page.getByRole('button',{name:'Save draft version',exact:true}).click();await saved(page);
 const familyBefore=await documentRecord('Orientation review packet').locator('.task-facts').innerText();
 await documentRecord('Orientation review packet').getByRole('button',{name:'Add revision',exact:true}).click();
 await page.getByLabel('Document title',{exact:true}).fill('Revised orientation packet');
 await page.getByLabel('Version content',{exact:true}).fill('Revised synthetic orientation packet with clear handoff responsibilities.');
 await page.getByRole('button',{name:'Save draft version',exact:true}).click();await saved(page);
 const familyAfter=await documentRecord('Revised orientation packet').locator('.task-facts').innerText();assert.equal(familyBefore,familyAfter);
 assert.match(await documentRecord('Revised orientation packet').innerText(),/Version 2/);
 await revealHistory(documentRecord('Orientation review packet'));assert.match(await documentRecord('Orientation review packet').innerText(),/Initial synthetic orientation packet/);
 await reviewState('Revised orientation packet','Submit for review','Review','Ready for a second participant to review.');
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Accept version',exact:true}).count(),0);
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Return to draft',exact:true}).count(),0);
 await switchStudyIdentity('reviewer');
 assert.equal(await documentRecord('Revised orientation packet').getByRole('button',{name:'Accept version',exact:true}).count(),0);
 await reviewState('Revised orientation packet','Return to draft','Draft','Clarify who owns the remaining handoff question.');
 await switchStudyIdentity('alex');
 await reviewState('Revised orientation packet','Submit for review','Review','Ownership is clarified for the next review.');
 await switchStudyIdentity('lead');
 await reviewState('Revised orientation packet','Accept version','Accepted','Accept this internal working packet.');
 assert.match(await documentRecord('Revised orientation packet').locator('.task-facts').innerText(),/Accepted/i);
 await reviewState('Revised orientation packet','Supersede version','Superseded','Retain this version as the historical reference.');
 assert.match(await documentRecord('Revised orientation packet').locator('.task-facts').innerText(),/Superseded/i);
 await page.setViewportSize({width:390,height:844});await reflow(page);
 await page.screenshot({path:`${output}/document-review-mobile.png`,fullPage:true});
 console.log('PASS: stable document families and study review roles');
 // Capture once, then change live task/state. The returned captured packet stays byte-for-byte equivalent.
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();
 const seededSnapshot=page.locator('#handoff-list article').filter({has:page.getByRole('heading',{name:'Orientation handoff • synthetic example',exact:true})});
 await seededSnapshot.getByRole('button',{name:'View snapshot',exact:true}).click();
 await page.locator('#handoff-detail').getByRole('heading',{name:'Orientation handoff • synthetic example',exact:true}).waitFor();
 assert.match(await page.locator('#handoff-detail').innerText(),/Captured state: Accepted/i);
 const seedReviewHistory=page.locator('#handoff-detail summary').filter({hasText:'Captured review history'}).first();
 await seedReviewHistory.focus();await page.keyboard.press('Enter');
 assert.match(await page.locator('#handoff-detail').innerText(),/Draft → Review/);
 await page.keyboard.press('Enter');

 await page.getByLabel('Snapshot title',{exact:true}).fill('Reviewed orientation handoff');
 await page.getByLabel('Scope, assumptions, open questions, and owners',{exact:true}).fill('Synthetic scope: compare documentation approaches. Owner Alex; confirm the final checklist before resuming work.');
 const rejectedCapture=page.waitForResponse(r=>r.url().endsWith('/handoffs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Capture snapshot',exact:true}).click();assert.equal((await rejectedCapture).status(),400);
 await page.getByText('Your input is retained.',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('Snapshot title',{exact:true}).inputValue(),'Reviewed orientation handoff');
 await page.getByLabel('Evidence selection',{exact:true}).selectOption('explicit');
 await page.getByText('Choose explicit evidence (optional)',{exact:true}).click();
 await page.getByLabel('Revised orientation packet · document version 2',{exact:true}).check();
 await page.locator('#handoff-form label').filter({hasText:'Review the handoff checklist · task version'}).locator('input').check();
 const captureResponse=page.waitForResponse(r=>r.url().endsWith('/handoffs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Capture snapshot',exact:true}).click();const captureResult=await captureResponse;assert.equal(captureResult.status(),200);const captured=await captureResult.json();
 await page.getByText('Immutable handoff snapshot captured.',{exact:true}).waitFor();
 assert.equal(await page.locator(':focus').getAttribute('class'),'panel handoff-capture');
 await page.locator('#handoff-detail').getByRole('heading',{name:'Reviewed orientation handoff',exact:true}).waitFor();
 const capturedText=await page.locator('#handoff-detail').innerText();
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 await revealRecord(task);await task.getByRole('button',{name:'Update task',exact:true}).click();
 await page.getByLabel('Next action and context',{exact:true}).fill('Live task changed after the fixed handoff capture.');
 await page.getByRole('button',{name:'Save task',exact:true}).click();await saved(page);
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 for(const stage of ['Closed','Active']){const oldStageForm=await page.locator('#stage-form').elementHandle();await page.getByLabel('Workspace stage',{exact:true}).selectOption(stage);const response=page.waitForResponse(r=>r.url().endsWith('/stage')&&r.request().method()==='POST');await page.getByRole('button',{name:'Update stage',exact:true}).click();assert.equal((await response).status(),200);await page.waitForFunction(form=>!form.isConnected,oldStageForm);await page.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();await page.locator('main[aria-busy="true"]').waitFor({state:'detached'});}
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();
 const snapshotCard=page.locator('#handoff-list article').filter({has:page.getByRole('heading',{name:'Reviewed orientation handoff',exact:true})});
 const snapshotResponse=page.waitForResponse(r=>r.url().endsWith('/handoffs/'+captured.id)&&r.request().method()==='GET');
 await snapshotCard.getByRole('button',{name:'View snapshot',exact:true}).click();const viewed=await(await snapshotResponse).json();assert.deepEqual(viewed,captured);
 await page.locator('#handoff-detail').getByRole('heading',{name:'Reviewed orientation handoff',exact:true}).waitFor();assert.equal(await page.locator('#handoff-detail').innerText(),capturedText);
 assert.equal(await page.locator('#handoff-detail').getByText('Live task changed after the fixed handoff capture.',{exact:true}).count(),0);
 await reflow(page);await page.screenshot({path:`${output}/handoff-mobile.png`,fullPage:true});
 console.log('PASS: immutable handoff and lifecycle recovery');
 // Returning collaborators retain personal acknowledgments without sharing them with peers.
 await page.getByRole('link',{name:'Overview',exact:true}).click();
 await page.getByRole('heading',{name:'Your study orientation',exact:true}).waitFor();
 const firstStep=page.locator('[data-onboarding-step]:not([disabled])').first();
 const orientationId=await firstStep.getAttribute('id');assert.equal(await firstStep.isChecked(),false);
 const initialResume=await page.locator('.orientation-resume a').getAttribute('href');
 await firstStep.focus();const acknowledged=page.waitForResponse(r=>r.url().endsWith('/onboarding')&&r.request().method()==='POST');
 await page.keyboard.press('Space');assert.equal((await acknowledged).status(),200);
 await page.getByText('Orientation step acknowledged for the current evidence.',{exact:true}).waitFor();
 assert.equal(await page.locator(':focus').getAttribute('id'),orientationId);
 await page.reload();await page.getByRole('heading',{name:'Your study orientation',exact:true}).waitFor();assert.equal(await page.locator('#'+orientationId).isChecked(),true);
 const nextResume=await page.locator('.orientation-resume a').getAttribute('href');assert.notEqual(nextResume,initialResume);await page.locator('.orientation-resume a').click();await page.waitForURL(current=>current.hash===nextResume);await page.getByRole('link',{name:'Overview',exact:true}).click();await page.getByRole('heading',{name:'Your study orientation',exact:true}).waitFor();
 await switchStudyIdentity('alex');await page.getByRole('link',{name:'Overview',exact:true}).click();await page.getByRole('heading',{name:'Your study orientation',exact:true}).waitFor();assert.equal(await page.locator('#'+orientationId).isChecked(),false);
 const alexStep=page.locator('[data-onboarding-step]:not([disabled])').nth(1);const alexStepId=await alexStep.getAttribute('id');
 const alexAcknowledged=page.waitForResponse(r=>r.url().endsWith('/onboarding')&&r.request().method()==='POST');await alexStep.check();assert.equal((await alexAcknowledged).status(),200);
 await page.getByText('Orientation step acknowledged for the current evidence.',{exact:true}).waitFor();
 await switchStudyIdentity('lead');await page.getByRole('link',{name:'Overview',exact:true}).click();await page.getByRole('heading',{name:'Your study orientation',exact:true}).waitFor();
 assert.equal(await page.locator('#'+orientationId).isChecked(),true);assert.equal(await page.locator('#'+alexStepId).isChecked(),false);
 for(let n=0;n<8&&await page.locator('[data-onboarding-step]:not([disabled]):not(:checked)').count();n++){const box=page.locator('[data-onboarding-step]:not([disabled]):not(:checked)').first();const oldBox=await box.elementHandle();const response=page.waitForResponse(r=>r.url().endsWith('/onboarding')&&r.request().method()==='POST');await box.check();assert.equal((await response).status(),200);await page.waitForFunction(input=>!input.isConnected,oldBox);}
 await page.getByText('You have reviewed every currently available step. Return when the study evidence changes.',{exact:true}).waitFor();

 await reflow(page);assert.equal(await page.getByRole('main').count(),1);
 await auditPage('returning collaborator');
 await page.screenshot({path:`${output}/returning-collaborator-mobile.png`,fullPage:true});
 console.log('PASS: personal returning-collaborator persistence, isolation and keyboard focus');
 await page.getByRole('link',{name:'Ideas & whiteboards',exact:true}).click();
 await page.getByRole('button',{name:'New session',exact:true}).click();
 await page.getByLabel('Session title',{exact:true}).fill('Prepare the next orientation');
 await page.getByLabel('Session purpose',{exact:true}).fill('Compare two practical ways to preserve context for returning collaborators.');
 await page.getByLabel('Responsible participant',{exact:true}).selectOption('lead');
 await page.getByRole('button',{name:'Save session',exact:true}).click();
 await page.locator('#board-title').getByText('Prepare the next orientation',{exact:true}).waitFor();
 const boardUrl=page.url();
 const createIdea=async(title,body)=>{await page.getByRole('button',{name:'Add idea',exact:true}).click();await page.getByLabel('Idea title',{exact:true}).fill(title);await page.getByLabel('Idea content',{exact:true}).fill(body);await page.getByRole('button',{name:'Save idea',exact:true}).click();await page.locator('#board-idea-form').waitFor({state:'detached'});await page.locator('.board-idea-card').filter({has:page.getByRole('heading',{name:title,exact:true})}).waitFor();};
 await createIdea('Checklist first','Start with a brief checklist and retain the linked evidence.');
 await createIdea('Conversation first','Start by reading the unresolved conversation.');
 let ideaCard=page.locator('.board-idea-card').filter({has:page.getByRole('heading',{name:'Checklist first',exact:true})});
 const logicalIdeaId=await ideaCard.getAttribute('data-idea');
 const reorderResponse=page.waitForResponse(r=>r.url().endsWith('/reorder')&&r.request().method()==='POST');
 await ideaCard.getByRole('button',{name:'Move Checklist first down',exact:true}).focus();await page.keyboard.press('Enter');assert.equal((await reorderResponse).status(),200);
 await page.locator('#board-live').getByText('Checklist first moved to position 2 of 2.',{exact:true}).waitFor();
 assert.equal(await page.locator(':focus').getAttribute('id'),'board-idea-'+logicalIdeaId);
 assert.equal(await page.locator('.board-ordered-list > li').nth(1).getAttribute('data-idea'),logicalIdeaId);
 await ideaCard.getByRole('button',{name:'Edit idea',exact:true}).click();
 await page.getByLabel('Idea title',{exact:true}).fill('Checklist with accountable owners');
 await page.getByLabel('Idea content',{exact:true}).fill('Keep the brief checklist and show the owner of each unresolved action.');
 await page.getByRole('button',{name:'Save idea',exact:true}).click();await page.locator('#board-idea-form').waitFor({state:'detached'});
 ideaCard=page.locator('.board-idea-card').filter({has:page.getByRole('heading',{name:'Checklist with accountable owners',exact:true})});
 await ideaCard.getByText('Idea history & decisions (2 versions)',{exact:true}).click();assert.match(await ideaCard.innerText(),/Start with a brief checklist/);
 const historicalDecision=ideaCard.getByRole('button',{name:'Decide from version 1',exact:true});const sourceVersion=await historicalDecision.getAttribute('data-version');await historicalDecision.click();
 await page.getByLabel('Decision title',{exact:true}).fill('Use the original checklist as the baseline');
 await page.getByLabel('Decision and rationale',{exact:true}).fill('The first proposal is the baseline; owner detail remains an alternative revision.');
 await page.getByRole('button',{name:'Save linked decision',exact:true}).click();await page.locator('#board-decision-form').waitFor({state:'detached'});
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();
 const boardDecision=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Use the original checklist as the baseline',exact:true})});await boardDecision.waitFor();
 assert.match(await boardDecision.innerText(),/Exact idea version 1/);assert((await boardDecision.innerText()).includes(sourceVersion));
 await boardDecision.getByRole('link',{name:'View source session',exact:true}).click();await page.locator('#board-title').getByText('Prepare the next orientation',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Readable summary',exact:true}).click();await page.getByRole('heading',{name:'Readable session summary',exact:true}).waitFor();
 assert.equal(await page.locator(':focus').getAttribute('class'),'board-readable');assert.match(await page.locator('.board-readable').innerText(),/cites idea version 1/);
 const summaryDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download summary',exact:true}).click();const summaryText=await readFile(await(await summaryDownload).path(),'utf8');
 assert.match(summaryText,/Checklist first/);assert.match(summaryText,/Checklist with accountable owners/);assert.match(summaryText,/Use the original checklist as the baseline/);
 await page.getByRole('button',{name:'Archive session',exact:true}).click();await page.getByLabel('Reason for session-state change',{exact:true}).fill('Pause this session while its baseline is reviewed.');
 await page.getByRole('button',{name:'Confirm archive',exact:true}).click();await page.locator('#board-state-form').waitFor({state:'detached'});
 assert.equal(await page.getByRole('button',{name:'Add idea',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Edit idea',exact:true}).count(),0);
 await page.getByRole('button',{name:'Readable summary',exact:true}).click();await page.getByRole('heading',{name:'Readable session summary',exact:true}).waitFor();
 await page.getByRole('button',{name:'Reopen session',exact:true}).click();await page.getByLabel('Reason for session-state change',{exact:true}).fill('Resume the next orientation discussion.');await page.getByRole('button',{name:'Confirm reopen',exact:true}).click();await page.locator('#board-state-form').waitFor({state:'detached'});
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 const closedForm=await page.locator('#stage-form').elementHandle();await page.getByLabel('Workspace stage',{exact:true}).selectOption('Closed');
 const studyClose=page.waitForResponse(r=>r.url().endsWith('/stage')&&r.request().method()==='POST');await page.getByRole('button',{name:'Update stage',exact:true}).click();assert.equal((await studyClose).status(),200);await page.waitForFunction(form=>!form.isConnected,closedForm);
 await page.goto(boardUrl);await page.locator('#board-title').getByText('Prepare the next orientation',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Add idea',exact:true}).click();await page.getByLabel('Idea title',{exact:true}).fill('Draft while closed');await page.getByLabel('Idea content',{exact:true}).fill('Preserve this draft when the closed study rejects editing.');
 const closedIdea=page.waitForResponse(r=>r.url().endsWith('/ideas')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save idea',exact:true}).click();assert.equal((await closedIdea).status(),409);
 await page.getByText('Your draft is retained.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Idea title',{exact:true}).inputValue(),'Draft while closed');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 const reopenedForm=await page.locator('#stage-form').elementHandle();await page.getByLabel('Workspace stage',{exact:true}).selectOption('Active');const studyReopen=page.waitForResponse(r=>r.url().endsWith('/stage')&&r.request().method()==='POST');await page.getByRole('button',{name:'Update stage',exact:true}).click();assert.equal((await studyReopen).status(),200);await page.waitForFunction(form=>!form.isConnected,reopenedForm);
 await page.goto(boardUrl);await page.locator('#board-title').getByText('Prepare the next orientation',{exact:true}).waitFor();await createIdea('Resume with context','Continue the reopened study without losing earlier reasoning.');
 await reflow(page);assert.equal(await page.locator('#board-live').getAttribute('role'),'status');assert.equal(await page.locator('#board-live').getAttribute('aria-live'),'polite');
 await auditPage('idea session');
 await page.screenshot({path:`${output}/brainstorm-session-mobile.png`,fullPage:true});
 await verifyExactIdeaLinks();
 console.log('PASS: all prior workflows and exact idea navigation');
 await page.locator('#identity').selectOption('lead');await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();await page.getByRole('button',{name:'+ Record a decision',exact:true}).click();
 await page.getByLabel('Decision title',{exact:true}).fill('Choose the concise orientation guide');
 const originalRationale='Use a concise guide as the working baseline. Preserve the alternative and the exact rationale.';
 await page.getByLabel('Decision and rationale',{exact:true}).fill(originalRationale);
 await page.getByLabel('Alternatives considered',{exact:true}).fill('A paired checklist and discussion guide is the alternative.');
 await page.getByLabel('Decision owner',{exact:true}).selectOption('lead');await page.getByLabel('Effective date',{exact:true}).fill('2026-10-08');
 await page.getByRole('button',{name:'Save decision',exact:true}).click();await saved(page);
 const originalDecision=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Choose the concise orientation guide',exact:true,includeHidden:true})});
 const originalDecisionId=(await originalDecision.getAttribute('id')).replace('record-','');
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();
 await page.getByLabel('Snapshot title',{exact:true}).fill('Decision baseline before supersession');
 await page.getByLabel('Scope, assumptions, open questions, and owners',{exact:true}).fill('Capture the original working choice and rationale before the team considers its successor.');
 await page.getByLabel('Evidence selection',{exact:true}).selectOption('explicit');await page.getByText('Choose explicit evidence (optional)',{exact:true}).click();
 await page.locator('#handoff-form input[name=itemIds][value="'+originalDecisionId+'"]').check();
 const originalCaptureResponse=page.waitForResponse(r=>r.url().endsWith('/handoffs')&&r.request().method()==='POST');await page.getByRole('button',{name:'Capture snapshot',exact:true}).click();const originalCaptureResult=await originalCaptureResponse;assert.equal(originalCaptureResult.status(),200);const originalDecisionCapture=await originalCaptureResult.json();await page.getByText('Immutable handoff snapshot captured.',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();await originalDecision.getByRole('button',{name:'Supersede decision',exact:true}).click();
 await page.getByLabel('Decision title',{exact:true}).fill('Use a paired orientation guide');await page.getByLabel('Decision and rationale',{exact:true}).fill('Use the concise checklist together with a short discussion guide for richer context.');
 await page.getByLabel('Reason for superseding',{exact:true}).fill('The rehearsal showed that unresolved questions need to accompany the checklist.');
 await page.getByRole('button',{name:'Save superseding decision',exact:true}).click();await saved(page);
 assert.equal(await page.locator('.decisions-current').getByRole('heading',{name:'Choose the concise orientation guide',exact:true}).count(),0);
 await page.locator('.decision-history > summary').click();await originalDecision.waitFor();assert.match(await originalDecision.innerText(),/Superseded decision/i);assert((await originalDecision.innerText()).includes(originalRationale));
 const successor=page.locator('.decisions-current article.record').filter({has:page.getByRole('heading',{name:'Use a paired orientation guide',exact:true})});assert.match(await successor.innerText(),/Current decision/i);
 await page.locator('.decision-history > summary').click();await successor.getByRole('link',{name:'Choose the concise orientation guide · decision version 1',exact:true}).click();await originalDecision.waitFor();assert.equal(await page.locator(':focus').getAttribute('id'),'record-'+originalDecisionId);
 await reflow(page);await auditPage('decision supersession and history');await page.screenshot({path:`${output}/decisions-mobile.png`,fullPage:true});
 await page.getByRole('link',{name:'Handoff snapshots',exact:true}).click();const baselineCard=page.locator('#handoff-list article').filter({has:page.getByRole('heading',{name:'Decision baseline before supersession',exact:true})});
 const baselineRead=page.waitForResponse(r=>r.url().endsWith('/handoffs/'+originalDecisionCapture.id)&&r.request().method()==='GET');await baselineCard.getByRole('button',{name:'View snapshot',exact:true}).click();assert.deepEqual(await(await baselineRead).json(),originalDecisionCapture);await page.locator('#handoff-detail').getByRole('heading',{name:'Decision baseline before supersession',exact:true}).waitFor();assert((await page.locator('#handoff-detail').innerText()).includes(originalRationale));assert.equal(await page.locator('#handoff-detail').getByRole('heading',{name:'Use a paired orientation guide',exact:true}).count(),0);
 await page.getByRole('link',{name:'Living documentation',exact:true}).click();await page.getByRole('button',{name:'Use Collaborator orientation template',exact:true}).click();
 const suggested=await page.getByLabel('Version content',{exact:true}).inputValue();assert.match(suggested,/People and responsibilities/);assert.match(suggested,/Read first/);assert.match(suggested,/Local resources/);
 await page.getByLabel('Document title',{exact:true}).fill('Orientation draft from the template');await page.getByLabel('Version content',{exact:true}).fill(suggested+'\n\nSynthetic walkthrough note: confirm ownership before the next handoff.');await page.getByRole('button',{name:'Save draft version',exact:true}).click();await saved(page);
 const templatedDocument=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Orientation draft from the template',exact:true})});await templatedDocument.waitFor();assert.match(await templatedDocument.locator('.task-facts').innerText(),/Draft/i);assert.match(await templatedDocument.innerText(),/Synthetic walkthrough note/);
 await page.getByRole('link',{name:'Living documentation',exact:true}).click();await page.getByRole('button',{name:'Add resource pointer',exact:true}).click();
 await page.getByLabel('Resource title',{exact:true}).fill('Synthetic methods reference');await page.getByLabel('Resource URL (optional)',{exact:true}).fill('https://synthetic@example.invalid/reference');await page.getByLabel('Local description or access guidance',{exact:true}).fill('Check the owner and existing access route before using this reference.');await page.getByLabel('Pointer owner',{exact:true}).selectOption('lead');await page.getByLabel('Source of this information',{exact:true}).fill('Synthetic documentation register');await page.getByLabel('Last verified date',{exact:true}).fill('2020-02-03');
 const rejectedPointer=page.waitForResponse(r=>r.url().endsWith('/resources')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save resource pointer',exact:true}).click();assert.equal((await rejectedPointer).status(),400);await page.getByText('Your pointer draft is retained.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Resource title',{exact:true}).inputValue(),'Synthetic methods reference');
 await page.getByLabel('Resource URL (optional)',{exact:true}).fill('https://example.invalid/reference');const pointerResponse=page.waitForResponse(r=>r.url().endsWith('/resources')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save resource pointer',exact:true}).click();assert.equal((await pointerResponse).status(),200);await page.getByText('Resource pointer saved. No destination was contacted.',{exact:true}).waitFor();
 const pointer=page.locator('.resource-pointer').filter({has:page.getByRole('heading',{name:'Synthetic methods reference',exact:true})});await pointer.waitFor();assert.match(await pointer.innerText(),/Riley/);assert.match(await pointer.innerText(),/2020-02-03/);assert.match(await pointer.innerText(),/Synthetic documentation register/);assert.match(await pointer.innerText(),/Review freshness/i);assert.equal(await pointer.getByRole('link').getAttribute('href'),'https://example.invalid/reference');
 await reflow(page);await auditPage('templates and resource pointers');await page.screenshot({path:`${output}/templates-resources-mobile.png`,fullPage:true});
 assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
 console.log('PASS: keyboard skip link, structured task create/edit/history/evidence, conflict draft recovery, identity isolation, mobile reflow, upload/download bytes and versions, quarantine, oversize error, explicit protocol retention, exact file citations, stale admin rejection, connected import preview/apply/repeat, stable document families and review roles, immutable handoff after edits and lifecycle changes, personal onboarding isolation, keyboard idea sessions and exact decision provenance, session/study lifecycle recovery, immutable decision supersession, template drafts and governed resource pointers, no page errors or external requests.');
}
} catch(error){await page.screenshot({path:`${output}/failure.png`,fullPage:true}).catch(()=>{});console.error('Browser failure location:',page.url());throw error;} finally {await browser.close();}
