// Independent milestone9 browser checks against an already-running disposable loopback demo.
// Supply Playwright via NODE_PATH or PLAYWRIGHT_MODULE; the harness never starts/stops a server.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';
assert(['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname),'Use loopback only');
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/milestone9-browser';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:390,height:844}});context.setDefaultTimeout(15000);
const page=await context.newPage(),errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});
const ready=async()=>page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
const switchIdentity=async id=>{await page.locator('#identity').selectOption(id);await ready();await page.getByText('Demo identity changed. Accessible studies have been refreshed.',{exact:true}).waitFor();};
const responseFor=suffix=>page.waitForResponse(r=>r.url().endsWith(suffix)&&r.request().method()==='POST');
const reflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390,'No horizontal page overflow');
async function audit(label){await reflow();if(process.env.HUB_BROWSER_AXE==='true'){const AxeBuilder=require('@axe-core/playwright').default;const result=await new AxeBuilder({page}).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],label);console.log('AXE: '+label+' — 0 violations');}}
try {
 await page.goto(base);await ready();await switchIdentity('admin');await page.getByRole('link',{name:'Administration',exact:true}).click();
 if(process.env.HUB_BROWSER_FOCUS!=='after-provision'){
 const beforeConfig=await(await context.request.get(base+'/api/admin')).json();
 const fillStudy=async()=>{await page.getByLabel('Study identifier',{exact:true}).fill('browser-study');await page.getByLabel('Study title',{exact:true}).fill('Synthetic browser provisioned study');await page.getByLabel('Study purpose and scope',{exact:true}).fill('An empty synthetic workspace for a controlled migration rehearsal.');await page.getByLabel('Existing synthetic directory group',{exact:true}).selectOption('demo-group-a');};
 await fillStudy();const provision=responseFor('/api/admin/studies');await page.getByRole('button',{name:'Create paused study',exact:true}).click();assert.equal((await provision).status(),200);await page.getByText('Synthetic study browser-study created in Paused state.',{exact:false}).waitFor();
 const afterConfig=await(await context.request.get(base+'/api/admin')).json();assert.deepEqual(afterConfig.groups,beforeConfig.groups,'Provisioning must not mutate group membership');assert.equal((await context.request.get(base+'/api/studies/browser-study')).status(),404,'Administrator role alone grants no content access');assert.equal(afterConfig.mappings.find(m=>m.studyId==='browser-study').stage,'Paused');
 // A repeated user attempt cannot silently overwrite an existing workspace.
 await fillStudy();const duplicate=responseFor('/api/admin/studies');await page.getByRole('button',{name:'Create paused study',exact:true}).click();assert.equal((await duplicate).status(),409);await page.getByText('Your study draft is retained.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Study title',{exact:true}).inputValue(),'Synthetic browser provisioned study');await audit('study provisioning and duplicate recovery');
 }
 await page.getByLabel('Synthetic identity',{exact:true}).selectOption('alex');await page.getByLabel('Application role',{exact:true}).selectOption('Administrator');const grant=responseFor('/api/admin/role');await page.getByRole('button',{name:'Save role',exact:true}).click();assert.equal((await grant).status(),200);await page.locator('#role-form').getByRole('option',{name:'Alex • synthetic researcher (Administrator)',exact:true}).waitFor({state:'attached'});await switchIdentity('alex');
 await page.getByRole('link',{name:'Synthetic browser provisioned study',exact:true}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();assert(!await page.locator('main').innerText().then(t=>t.includes('Sam · synthetic study contact')));assert.match(await page.locator('main').innerText(),/Paused/);const provisioned=await(await context.request.get(base+'/api/studies/browser-study')).json();assert.equal(provisioned.items.length,0);await audit('empty provisioned member workspace');await page.screenshot({path:output+'/provisioned-study-mobile.png',fullPage:true});
 await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();await page.getByLabel('Workspace stage',{exact:true}).selectOption('Active');await page.getByRole('button',{name:'Update stage',exact:true}).click();await page.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();
 const studyPath='/api/studies/browser-study';const getStudy=async()=>{const r=await context.request.get(base+studyPath);assert.equal(r.status(),200);return r.json();};const projection=study=>({items:study.items,files:study.files,importLedger:study.importLedger,currentProtocol:study.currentProtocol});const original=projection(await getStudy());
 const manifest=JSON.parse(await readFile(new URL('../fixtures/app-import.json',import.meta.url),'utf8'));const choose=async(label,value)=>page.getByLabel(label,{exact:true}).setInputFiles({name:'synthetic-rehearsal.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
 await page.waitForFunction(()=>document.querySelector('#rehearsal-create-form')?.dataset.revision);await choose('Rehearsal manifest JSON',manifest);const prepared=responseFor('/imports/rehearsals');await page.getByRole('button',{name:'Prepare isolated rehearsal',exact:true}).click();const preparedResponse=await prepared;assert.equal(preparedResponse.status(),200);let detail=await preparedResponse.json();const sessionId=detail.id;assert.equal(detail.inventory.length,7);assert.equal(detail.state,'Ready');assert.equal(detail.branchSha256,detail.baselineSha256);await page.getByRole('heading',{name:'Isolated rehearsal inventory',exact:true}).waitFor();
 const action=async(label,expected)=>{const r=responseFor('/'+sessionId+'/actions');await page.getByRole('button',{name:label,exact:true}).click();const result=await r;assert.equal(result.status(),200);detail=await result.json();assert.equal(detail.state,expected);await page.locator('#rehearsal-detail .pill').filter({hasText:expected}).waitFor();return detail;};
 await action('Abort rehearsal step','Aborted');assert.equal(detail.branchSha256,detail.baselineSha256);await action('Retry saved manifest','Ready');
 const stale=await context.newPage();await stale.goto(base+'/#study/browser-study/activity');await stale.getByRole('button',{name:'Open rehearsal '+sessionId,exact:true}).click();await stale.getByRole('button',{name:'Apply to isolated branch',exact:true}).waitFor();
 await action('Apply to isolated branch','Applied');assert.equal(detail.report.counts.imported,7);assert.equal(detail.branchSummary.items,4);assert.equal(detail.branchSummary.files,3);assert.notEqual(detail.branchSha256,detail.baselineSha256);
 const staleResponse=stale.waitForResponse(r=>r.url().endsWith('/'+sessionId+'/actions')&&r.request().method()==='POST');await stale.getByRole('button',{name:'Apply to isolated branch',exact:true}).click();assert.equal((await staleResponse).status(),409);await stale.getByText('The rehearsal controls and chosen manifest remain available.',{exact:false}).waitFor();await stale.close();
 const appliedHash=detail.branchSha256;const delta=structuredClone(manifest);delta.records.find(record=>record.source_id==='document-1').title='Conflicting same-revision synthetic title';await choose('Delta manifest JSON',delta);const deltaResponse=responseFor('/'+sessionId+'/actions');await page.getByRole('button',{name:'Preview branch delta',exact:true}).click();assert.equal((await deltaResponse).status(),200);detail=await(await context.request.get(base+studyPath+'/imports/rehearsals/'+sessionId)).json();assert.equal(detail.state,'Ready');assert(detail.inventory.some(entry=>entry.sourceId==='document-1'&&entry.outcome==='quarantined'));assert.equal(detail.branchSha256,appliedHash);await action('Apply to isolated branch','Applied');assert.equal(detail.report.counts.imported,0);assert(detail.report.counts.quarantined>0);assert.equal(detail.branchSummary.items,4);assert.equal(detail.branchSummary.files,3);
 await action('Roll back isolated branch','RolledBack');assert.equal(detail.branchSha256,detail.baselineSha256);assert.deepEqual(projection(await getStudy()),original,'Rollback/rehearsal must leave original study content intact');
 const receiptDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download rehearsal metadata receipt',exact:true}).click();const exported=JSON.parse(await readFile(await(await receiptDownload).path(),'utf8'));const receipt=exported.receipt;assert.match(exported.receiptSha256,/^[A-F0-9]{64}$/);assert.deepEqual(receipt,detail);assert.equal(receipt.branchSha256,receipt.baselineSha256);assert.equal(receipt.state,'RolledBack');assert.equal(await page.locator('#rehearsal-detail a[href*="/download"]').count(),0,'Metadata rehearsals must not expose simulated file downloads');
 const table=page.getByRole('region',{name:'Scrollable rehearsal inventory',exact:true});await table.focus();assert.equal(await page.locator(':focus').getAttribute('aria-label'),'Scrollable rehearsal inventory');await audit('isolated inventory, interrupted retry and rollback');await page.screenshot({path:output+'/rehearsal-mobile.png',fullPage:true});
 // Commit an explicitly synthetic fixture separately to exercise the real local source-link resolver.
 await choose('Synthetic manifest JSON',manifest);const preview=responseFor('/imports/preview');await page.getByRole('button',{name:'Preview import',exact:true}).click();assert.equal((await preview).status(),200);const imported=responseFor('/imports/apply');await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).click();assert.equal((await imported).status(),200);await page.getByText('Synthetic import applied. Review accepted and quarantined outcomes in the saved report.',{exact:true}).waitFor();
 async function resolve(sourceId){await page.getByLabel('Source study identifier',{exact:true}).fill('synthetic-study');await page.getByLabel('Source record identifier',{exact:true}).fill(sourceId);const response=page.waitForResponse(r=>r.url().includes('/api/resolve?'));await page.getByRole('button',{name:'Find local record',exact:true}).click();return response;}
 const resolved=await resolve('version-1');assert.equal(resolved.status(),200);const target=await resolved.json();assert(target.href.startsWith('#study/browser-study/document/'));const legacyUrl=manifest.records.find(record=>record.source_id==='document-1').legacy_url;const legacy=await context.request.get(base+'/api/resolve?'+new URLSearchParams({studyId:'browser-study',sourceUrl:legacyUrl}));assert.equal(legacy.status(),200);assert((await legacy.json()).href.startsWith('#study/browser-study/'));assert.equal(legacy.headers().location,undefined);await page.locator('#source-link-result a').click();const targetId=decodeURIComponent(target.href.split('/').at(-1));await page.locator('#record-'+targetId).waitFor();assert.equal(await page.locator(':focus').getAttribute('id'),'record-'+targetId);await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 const deletedTarget=await resolve('decision-1');assert.equal(deletedTarget.status(),200);const deletedLink=await deletedTarget.json();const deletedId=decodeURIComponent(deletedLink.href.split('/').at(-1));const session=await(await context.request.get(base+'/api/session')).json();const latest=await getStudy();const removed=await context.request.post(base+studyPath+'/items/'+deletedId+'/delete',{headers:{'X-CSRF-TOKEN':session.csrf},data:{expectedRevision:latest.revision,requestId:crypto.randomUUID()}});assert.equal(removed.status(),200);const unavailable=await resolve('decision-1');assert.equal(unavailable.status(),404);await page.getByText('No available migrated record matches this link in the selected study.',{exact:true}).waitFor();assert.equal(await page.locator('#source-link-result a').count(),0);await audit('permission-aware migrated source resolver');
 await switchIdentity('sam');assert.equal(await page.getByRole('link',{name:'Synthetic browser provisioned study',exact:true}).count(),0);const denied=await context.request.get(base+'/api/resolve?'+new URLSearchParams({studyId:'browser-study',sourceStudyId:'synthetic-study',sourceId:'version-1'}));assert.equal(denied.status(),404);assert.deepEqual(await denied.json(),await unavailable.json());assert.equal((await context.request.get(base+studyPath+'/imports/rehearsals/'+sessionId+'/export')).status(),404);
 const samSession=await(await context.request.get(base+'/api/session')).json();const unauthorized=await context.request.post(base+'/api/admin/studies',{headers:{'X-CSRF-TOKEN':samSession.csrf},data:{studyId:'unauthorized-study',title:'Synthetic unauthorized attempt',summary:'Must not be created.',groupId:'demo-group-b',expectedRevision:1,requestId:crypto.randomUUID()}});assert.equal(unauthorized.status(),403);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(process.env.HUB_BROWSER_FOCUS?'PASS: focused post-provisioning triage only.':'PASS: paused existing-group provisioning without membership/admin-content grant, duplicate recovery, isolated inventory/abort/retry/stale conflict/delta quarantine/rollback, original content unchanged, exact migrated file focus, deleted/unauthorized resolver masking, keyboard/mobile and no external requests.');
} catch(error){await page.screenshot({path:output+'/failure.png',fullPage:true}).catch(()=>{});throw error;}finally{await browser.close();}
