// Independent milestone8 browser checks against an already-running disposable loopback demo.
// Supply Playwright via NODE_PATH or PLAYWRIGHT_MODULE; the harness never starts/stops a server.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';
assert(['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname),'Use loopback only');
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/milestone8-browser';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:390,height:844}});context.setDefaultTimeout(15000);
const page=await context.newPage(),errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});
const ready=async()=>page.getByRole('heading',{name:'My studies',exact:true}).waitFor();
const switchIdentity=async id=>{await page.locator('#identity').selectOption(id);await ready();await page.getByText('Demo identity changed. Accessible studies have been refreshed.',{exact:false}).waitFor();};
const responseFor=suffix=>page.waitForResponse(r=>r.url().endsWith(suffix)&&r.request().method()==='POST');
const reflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390,'No horizontal page overflow');
async function audit(label){await reflow();if(process.env.HUB_BROWSER_AXE==='true'){const AxeBuilder=require('@axe-core/playwright').default;const result=await new AxeBuilder({page}).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],label);console.log('AXE: '+label+' — 0 violations');}}
try {
 await page.goto(base);await ready();let receipt;
 if(process.env.HUB_BROWSER_FOCUS!=='resources'){await switchIdentity('admin');await page.getByRole('link',{name:'Administration',exact:true}).click();
 await page.getByLabel('Synthetic identity',{exact:true}).selectOption('alex');await page.getByLabel('Application role',{exact:true}).selectOption('Administrator');
 const grant=responseFor('/api/admin/role');await page.getByRole('button',{name:'Save role',exact:true}).click();assert.equal((await grant).status(),200);await page.locator('#role-form').getByRole('option',{name:'Alex • synthetic researcher (Administrator)',exact:true}).waitFor({state:'attached'});await switchIdentity('alex');
 assert.equal(await page.getByRole('link',{name:'Open workspace'}).count(),1);await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('link',{name:'Activity & lifecycle',exact:true}).click();
 const manifest=JSON.parse(await readFile(new URL('../fixtures/app-import.json',import.meta.url),'utf8'));const exception=structuredClone(manifest.records.find(r=>r.kind==='discussion'));exception.source_id='browser-exception';exception.author_id='unknown-synthetic-author';exception.references=[];exception.title='Unaccepted synthetic source';manifest.records=[exception];
 await page.getByLabel('Synthetic manifest JSON',{exact:true}).setInputFiles({name:'synthetic-exception.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(manifest))});
 const preview=responseFor('/imports/preview');await page.getByRole('button',{name:'Preview import',exact:true}).click();assert.equal((await preview).status(),200);
 const applied=responseFor('/imports/apply');await page.getByRole('button',{name:'Apply previewed manifest',exact:true}).click();const appliedResponse=await applied;assert.equal(appliedResponse.status(),200);const report=await appliedResponse.json();assert.equal(report.counts.quarantined,1);
 const caseCard=()=>page.locator('.exception-review > article.record').filter({has:page.getByRole('heading',{name:'browser-exception',exact:true})});
 await caseCard().waitFor();assert.match(await caseCard().innerText(),/quarantined/);
 async function review(action,disposition,note){await caseCard().getByRole('button',{name:'Review exception browser-exception',exact:true}).click();await page.getByLabel('Exception owner',{exact:true}).selectOption('alex');await page.getByLabel('Review action',{exact:true}).selectOption(action);await page.getByLabel('Disposition',{exact:true}).selectOption(disposition);await page.getByLabel('Review note',{exact:true}).fill(note);const result=responseFor('/'+report.id+'/review');await page.getByRole('button',{name:'Save exception review',exact:true}).click();assert.equal((await result).status(),200);await page.locator('#import-case-form').waitFor({state:'detached'});}
 await review('Assign','NeedsCorrection','Assign responsibility for a synthetic unmapped author.');await review('Review','NeedsCorrection','Retain the exception until the source author is corrected.');
 // Resolving without an allowed disposition is rejected and preserves the operator draft.
 await caseCard().getByRole('button',{name:'Review exception browser-exception',exact:true}).click();await page.getByLabel('Review action',{exact:true}).selectOption('Resolve');await page.locator('#exception-disposition').evaluate(select=>{select.add(new Option('Tampered invalid disposition','NeedsCorrection'));select.value='NeedsCorrection';});await page.getByLabel('Review note',{exact:true}).fill('This invalid resolution must remain a draft.');const invalid=responseFor('/'+report.id+'/review');await page.getByRole('button',{name:'Save exception review',exact:true}).click();assert.equal((await invalid).status(),400);await page.getByText('Your review draft is retained.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Review note',{exact:true}).inputValue(),'This invalid resolution must remain a draft.');
 await page.getByLabel('Disposition',{exact:true}).selectOption('Excluded');const resolved=responseFor('/'+report.id+'/review');await page.getByRole('button',{name:'Save exception review',exact:true}).click();assert.equal((await resolved).status(),200);await page.locator('#import-case-form').waitFor({state:'detached'});assert.match(await caseCard().innerText(),/Resolved/);
 await page.getByText('Saved import reports',{exact:true}).click();const capture=responseFor('/'+report.id+'/receipts');await page.getByRole('button',{name:'Capture batch receipt',exact:true}).click();const receiptResponse=await capture;assert.equal(receiptResponse.status(),200);receipt=await receiptResponse.json();await page.getByRole('heading',{name:'Captured batch receipt',exact:true}).waitFor();
 const downloadEvent=page.waitForEvent('download');await page.getByRole('link',{name:'Download receipt JSON',exact:true}).click();assert.deepEqual(JSON.parse(await readFile(await(await downloadEvent).path(),'utf8')),receipt);
 await review('Reopen','NeedsCorrection','A later source correction will be reviewed separately.');await page.getByRole('button',{name:'View captured receipt',exact:true}).click();await page.getByRole('heading',{name:'Captured batch receipt',exact:true}).waitFor();const retained=await context.request.get(base+'/api/studies/atlas/imports/receipts/'+receipt.id);assert.deepEqual(await retained.json(),receipt);assert.equal(receipt.cases[0].state,'Resolved');
 await caseCard().locator('summary').focus();await page.keyboard.press('Enter');assert.match(await caseCard().innerText(),/A later source correction/);await audit('import exception review and receipt');await page.screenshot({path:output+'/import-review-mobile.png',fullPage:true});
 const atlas=await(await context.request.get(base+'/api/studies/atlas')).json();assert(!atlas.items.some(i=>i.title==='Unaccepted synthetic source'),'Disposition must not promote quarantined content');
 }
 await switchIdentity('lead');await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('link',{name:'Living documentation',exact:true}).click();
 await page.getByRole('button',{name:'Create study template',exact:true}).click();await page.getByLabel('Template title',{exact:true}).fill('Synthetic review template');await page.getByLabel('Template description',{exact:true}).fill('A useful starting point for a synthetic review.');await page.getByLabel('Template starting content',{exact:true}).fill('Original definition: identify the evidence and responsible reviewer.');await page.getByLabel('Template change reason',{exact:true}).fill('Create a reusable review outline.');await page.getByRole('button',{name:'Save template version',exact:true}).click();await page.locator('#template-form').waitFor({state:'detached'});
 let template=page.locator('.template-card').filter({has:page.getByRole('heading',{name:'Synthetic review template',exact:true})});await template.getByRole('button',{name:'Use Synthetic review template template',exact:true}).click();await page.getByLabel('Document title',{exact:true}).fill('Draft from original review definition');await page.getByRole('button',{name:'Save draft version',exact:true}).click();await page.locator('#document-form').waitFor({state:'detached'});
 await page.getByRole('link',{name:'Living documentation',exact:true}).click();await template.getByRole('button',{name:'Revise template Synthetic review template',exact:true}).click();await page.getByLabel('Template starting content',{exact:true}).fill('Revised definition: add explicit owner confirmation.');await page.getByLabel('Template change reason',{exact:true}).fill('Clarify the ownership step.');await page.getByRole('button',{name:'Save template version',exact:true}).click();await page.locator('#template-form').waitFor({state:'detached'});
 await template.getByRole('button',{name:'Template history Synthetic review template',exact:true}).click();const oldTemplate=page.locator('#template-history details').filter({has:page.locator('summary').filter({hasText:'Definition version 1'})});await oldTemplate.locator('summary').focus();await page.keyboard.press('Enter');assert.match(await oldTemplate.innerText(),/Original definition/);await oldTemplate.getByRole('button',{name:'Use definition version 1',exact:true}).click();assert.match(await page.getByLabel('Version content',{exact:true}).inputValue(),/Original definition/);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('link',{name:'Document library',exact:true}).click();const draft=page.locator('article.record').filter({has:page.getByRole('heading',{name:'Draft from original review definition',exact:true})});await draft.waitFor();assert.match(await draft.innerText(),/Original definition/);assert.match(await draft.innerText(),/Definition version 1/);assert(!await draft.innerText().then(t=>t.includes('Revised definition')));
 await page.getByRole('link',{name:'Living documentation',exact:true}).click();await page.getByRole('button',{name:'Add resource pointer',exact:true}).click();await page.getByLabel('Resource title',{exact:true}).fill('Synthetic reviewer reference');await page.getByLabel('Resource URL (optional)',{exact:true}).fill('https://example.invalid/original');await page.getByLabel('Local description or access guidance',{exact:true}).fill('Original synthetic guidance.');await page.getByLabel('Pointer owner',{exact:true}).selectOption('reviewer');await page.getByLabel('Source of this information',{exact:true}).fill('Synthetic register one');await page.getByLabel('Last verified date',{exact:true}).fill('2020-02-03');await page.getByRole('button',{name:'Save resource pointer',exact:true}).click();await page.locator('#resource-form').waitFor({state:'detached'});
 const family=page.locator('.resource-family').filter({has:page.getByRole('heading',{name:'Synthetic reviewer reference',exact:true})});await family.getByRole('button',{name:'Replace pointer',exact:true}).click();await page.getByLabel('Resource URL (optional)',{exact:true}).fill('https://example.invalid/replacement');await page.getByLabel('Local description or access guidance',{exact:true}).fill('Replacement synthetic guidance.');await page.getByLabel('Pointer owner',{exact:true}).selectOption('lead');await page.getByLabel('Source of this information',{exact:true}).fill('Synthetic register two');await page.getByLabel('Reason for this revision',{exact:true}).fill('Replace a superseded reference.');await page.getByRole('button',{name:'Save resource pointer',exact:true}).click();await page.locator('#resource-form').waitFor({state:'detached'});
 const stalePointer=await context.newPage();await stalePointer.goto(base+'/#study/atlas/documentation');await stalePointer.getByRole('button',{name:'Record verification',exact:true}).click();await stalePointer.getByLabel('Reason for this revision',{exact:true}).fill('Preserve this stale verification draft.');
 await family.getByRole('button',{name:'Record verification',exact:true}).click();await page.getByLabel('Last verified date',{exact:true}).fill('2021-02-03');await page.getByLabel('Reason for this revision',{exact:true}).fill('Record a later synthetic verification.');await page.getByRole('button',{name:'Save resource pointer',exact:true}).click();await page.locator('#resource-form').waitFor({state:'detached'});const staleResult=stalePointer.waitForResponse(r=>r.url().endsWith('/reverify')&&r.request().method()==='POST');await stalePointer.getByRole('button',{name:'Save resource pointer',exact:true}).click();assert.equal((await staleResult).status(),409);await stalePointer.getByText('Your pointer draft is retained.',{exact:false}).waitFor();assert.equal(await stalePointer.getByLabel('Reason for this revision',{exact:true}).inputValue(),'Preserve this stale verification draft.');await stalePointer.close();await family.locator('summary').focus();await page.keyboard.press('Enter');assert.match(await family.innerText(),/Synthetic register one/);assert.match(await family.innerText(),/Casey/);assert.match(await family.innerText(),/2020-02-03/);assert.match(await family.innerText(),/Synthetic register two/);await audit('template definitions and retained resource history');await page.screenshot({path:output+'/resource-history-mobile.png',fullPage:true});
 await page.locator('#search').fill('Casey');await page.locator('#search-form button').click();await page.getByRole('heading',{name:'Search results',exact:true}).waitFor();await page.getByLabel('Study',{exact:true}).selectOption('atlas');await page.getByLabel('Record type',{exact:true}).selectOption('task');await page.getByRole('button',{name:'Apply search filters',exact:true}).click();await page.getByRole('link',{name:'Rehearse the returning-collaborator walkthrough',exact:true}).waitFor();assert.match(await page.locator('main').innerText(),/Assignee:.*Casey/);assert.equal(await page.getByLabel('Study',{exact:true}).locator('option[value=beacon]').count(),0);await audit('metadata search and filters');
 await page.locator('#search').fill('Unaccepted synthetic source');await page.locator('#search-form button').click();await page.getByRole('heading',{name:'No matching records'}).waitFor();await switchIdentity('sam');await page.locator('#search').fill('Synthetic reviewer reference');await page.locator('#search-form button').click();await page.getByRole('heading',{name:'No matching records'}).waitFor();if(receipt)assert.equal((await context.request.get(base+'/api/studies/atlas/imports/receipts/'+receipt.id+'/export')).status(),404);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(process.env.HUB_BROWSER_FOCUS==='resources'?'PASS: focused template/resource/search triage only.':'PASS: exception ownership/disposition/draft validation, immutable receipt/export/reopen, template version provenance, resource replacement/reverification history, displayed-assignee search and filters, keyboard/mobile, identity isolation and no external requests.');
} catch(error){await page.screenshot({path:output+'/failure.png',fullPage:true}).catch(()=>{});throw error;}finally{await browser.close();}
