// Independent real-component browser checks against an already-started fresh loopback demo.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.HUB_BROWSER_URL||'http://127.0.0.1:5080';assert(['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname));
const output=process.env.HUB_BROWSER_ARTIFACTS||'artifacts/uswds-browser';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:process.env.BROWSER_NO_SANDBOX==='true'?['--no-sandbox']:[]});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();context.setDefaultTimeout(15000);
const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url());});
async function audit(name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),page.viewportSize().width,'No page overflow: '+name);if(process.env.HUB_BROWSER_AXE==='true'){const AxeBuilder=require('@axe-core/playwright').default;const result=await new AxeBuilder({page}).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})),[],name);console.log('AXE: '+name+' — 0 violations');}await page.screenshot({path:output+'/'+name+'.png',fullPage:true});}
const primary=async name=>{const link=page.getByRole('link',{name,exact:true});if(!await link.isVisible())await page.getByRole('button',{name:'Menu',exact:true}).click();await link.click();};
try{
 await page.goto(base);await page.getByRole('heading',{name:'My studies',exact:true}).waitFor();assert.equal(await page.locator('.usa-card-group .usa-card .usa-card__container').count(),1);assert(await page.evaluate(()=>!!window.HubUSWDS?.accordion&&!!window.HubUSWDS?.fileInput));await audit('my-studies-desktop');
 await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').innerText(),'Skip to main content');await page.keyboard.press('Enter');assert.equal(await page.locator(':focus').getAttribute('id'),'main');
 await page.setViewportSize({width:390,height:844});await audit('my-studies-mobile');const menu=page.getByRole('button',{name:'Menu',exact:true});await menu.focus();await page.keyboard.press('Enter');await page.locator('.usa-nav.is-visible').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.usa-nav.is-visible').count(),0);assert(await menu.evaluate(e=>e===document.activeElement));await menu.click();await page.locator('.usa-nav__close').click();assert(await menu.evaluate(e=>e===document.activeElement));
 await page.getByRole('link',{name:'Open workspace'}).click();await page.getByRole('heading',{name:'At a glance',exact:true}).waitFor();assert.equal(await page.locator('.usa-sidenav a[aria-current=page]').count(),1);await audit('atlas-overview-mobile');await page.setViewportSize({width:1440,height:1000});await audit('atlas-overview-desktop');
 const box=page.locator('#onboarding-guidance');assert(await box.evaluate(e=>e.classList.contains('usa-checkbox__input')&&e.nextElementSibling?.htmlFor===e.id));await box.focus();const acknowledged=page.waitForResponse(r=>r.url().endsWith('/onboarding')&&r.request().method()==='POST');await page.keyboard.press('Space');assert.equal((await acknowledged).status(),200);await page.waitForFunction(()=>document.querySelector('#onboarding-guidance')?.checked);assert.equal(await page.locator(':focus').getAttribute('id'),'onboarding-guidance');
 await page.getByRole('link',{name:'Tasks & decisions',exact:true}).click();await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByLabel('Task title',{exact:true}).waitFor();await audit('task-form-desktop');await page.setViewportSize({width:390,height:844});await audit('task-form-mobile');await page.getByRole('button',{name:'Save task',exact:true}).click();const title=page.getByLabel('Task title',{exact:true});assert.equal(await title.getAttribute('aria-invalid'),'true');const described=(await title.getAttribute('aria-describedby')).split(/\s+/);assert(described.some(id=>id.endsWith('-validation-error')));assert(await page.locator('#'+described.find(id=>id.endsWith('-validation-error'))).innerText());const validationHash=await page.evaluate(()=>location.hash);await page.locator('.hub-validation-summary a').filter({hasText:'Task title:'}).click();assert.equal(await page.locator(':focus').getAttribute('id'),'item-title');assert.equal(await page.evaluate(()=>location.hash),validationHash);await title.fill('Synthetic keyboard task');assert.equal(await title.getAttribute('aria-invalid'),null);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('link',{name:'Document library',exact:true}).click();const history=page.locator('.document-family .version-disclosure .usa-accordion__button').first();await history.waitFor();assert.equal(await history.getAttribute('aria-expanded'),'false');const content=page.locator('#'+await history.getAttribute('aria-controls'));assert.equal(await content.isVisible(),false);await history.focus();await page.keyboard.press('Enter');assert.equal(await history.getAttribute('aria-expanded'),'true');await content.waitFor();const oldRecord=content.locator('article.record').first();const oldId=(await oldRecord.getAttribute('id')).replace(/^record-/,'');await history.press('Space');assert.equal(await history.getAttribute('aria-expanded'),'false');await page.evaluate(id=>{location.hash='#study/atlas/document/'+id;},oldId);await page.locator('#record-'+oldId).waitFor();assert.equal(await page.locator(':focus').getAttribute('id'),'record-'+oldId);await audit('history-deep-link-mobile');
 await page.getByRole('button',{name:'Upload file',exact:true}).click();const file=page.getByLabel('Choose file',{exact:true});assert.equal(await file.evaluate(e=>!!e.closest('.usa-file-input')),true);await file.setInputFiles({name:'synthetic-component.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic component upload bytes.')});assert.equal(await file.evaluate(e=>e.files[0].name),'synthetic-component.txt');await page.locator('.usa-file-input__preview-heading').waitFor();await audit('file-input-mobile');await page.locator('#upload-form button[type=submit]').click();await page.locator('#upload-form').waitFor({state:'detached'});await page.getByText('Saved. The shared record has been updated.',{exact:true}).waitFor();assert.equal(await page.locator('#notice.usa-alert .usa-alert__body').count(),1);
 await page.locator('#identity').selectOption('admin');await page.getByText('Demo identity changed. Accessible studies have been refreshed.',{exact:false}).waitFor();await primary('Administration');await page.locator('#role-form').waitFor();assert.equal(await page.locator('.usa-nav.is-visible').count(),0);await audit('administration-mobile');await page.setViewportSize({width:1440,height:1000});await audit('administration-desktop');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: local USWDS components, mobile menu Escape/close focus, skip link, cards/sidenav, keyboard checkbox persistence, native validation associations, accordion keyboard/history deep-link focus, enhanced file input/save, alerts, desktop/mobile reflow, no page errors/external requests.');
}catch(error){await page.screenshot({path:output+'/failure.png',fullPage:true});throw error;}finally{await browser.close();}
