import * as sass from 'sass';
import postcss from 'postcss';
import autoprefixer from 'autoprefixer';
import {build} from 'esbuild';
import {mkdir, writeFile, cp, copyFile} from 'node:fs/promises';
const destination='wwwroot/vendor/uswds';
await mkdir(`${destination}/css`,{recursive:true});
const compiled=sass.compile('assets/styles.scss',{loadPaths:['node_modules/@uswds/uswds/packages'],style:'compressed',quietDeps:true,silenceDeprecations:['import','global-builtin','color-functions','if-function']});
const css=await postcss([autoprefixer]).process(compiled.css,{from:undefined});
await writeFile(`${destination}/css/uswds.css`,css.css);
await cp('node_modules/@uswds/uswds/dist/fonts',`${destination}/fonts`,{recursive:true});
await cp('node_modules/@uswds/uswds/dist/img',`${destination}/img`,{recursive:true});
await copyFile('node_modules/@uswds/uswds/LICENSE.md',`${destination}/LICENSE.md`);
const app=sass.compile('assets/app.scss',{loadPaths:['node_modules/@uswds/uswds/packages'],style:'compressed',quietDeps:true,silenceDeprecations:['import','global-builtin','color-functions','if-function']});
await writeFile('wwwroot/app.css',(await postcss([autoprefixer]).process(app.css,{from:undefined})).css);
await mkdir(`${destination}/js`,{recursive:true});
await build({entryPoints:['assets/uswds-components-entry.js'],outfile:`${destination}/js/components.js`,bundle:true,minify:true,platform:'browser',target:['es2020'],legalComments:'none'});
await copyFile('node_modules/@uswds/uswds/dist/js/uswds-init.min.js',`${destination}/js/uswds-init.min.js`);
console.log('Built local USWDS component CSS/JavaScript, application layout CSS, fonts and images.');
